#                                    Python and Data Science

## *usando IPython

#### IPython introduces the ? character as a shorthand for accessing this documentation and other relevant information:

In [1]:
#len?


#### Importantly, this will even work for functions or other objects you create yourself! Here we’ll define a small function with a docstring:

To create a docstring for our function, we simply placed a string literal in the first line. 
By convention we used Python’s triple-quote notation for multiline strings ("""docstring"""). 

In [2]:
def square(a):
    """"Return the square of a."""
    return a ** 2
square(2)

4

In [3]:
#square?

To see a list of all available attributes of an object, you can type the name of the object followed by a period (.) character and the Tab key: 

In [4]:
L = [1,2,3]
#L.


We’ll start with the standard NumPy import, under the alias np:
    

In [5]:
import numpy as np

NumPy is constrained to arrays that all contain the same type. 
If types do not match, NumPy will upcast if possible (here, integers are upcast to floating point):

In [6]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:

Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy. Here are several examples:

In [11]:
np.ones(10, dtype=int)


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [8]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
 # Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
 # Create a 3x3 array of uniformly distributed
 # random values between 0 and 1
np.random.random((3, 3))

array([[0.41673749, 0.84070303, 0.12535396],
       [0.21839513, 0.20643462, 0.38993975],
       [0.04528478, 0.44767435, 0.96079852]])

In [16]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-2.32554617,  0.57028464, -1.80671112],
       [-0.43406214, -0.08554678, -0.73663412],
       [-1.13080282,  0.03819309,  0.12269682]])

In [17]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[3, 6, 4],
       [6, 0, 1],
       [3, 2, 2]])

In [19]:
 # Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])